declare module 'portable-fetch'
declare module 'react-password-strength'
declare module 'highcharts'
declare module 'highcharts/highstock'
declare module 'highcharts/modules/exporting'
declare module 'highcharts/modules/full-screen'
declare module 'highcharts/modules/offline-exporting'
declare module 'highcharts/modules/export-data'
